# Generated by Django 3.2.5 on 2021-07-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('prouct_quantity', models.BigIntegerField()),
                ('product_price', models.BigIntegerField()),
                ('product_image', models.ImageField(upload_to='product_image/')),
            ],
        ),
    ]
