# Generated by Django 3.2.5 on 2021-07-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210714_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='wear_by',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('topwear', 'TopWear'), ('bottomwear', 'BottomWear')], default='', max_length=50),
        ),
    ]
