# Generated by Django 3.2.5 on 2021-07-14 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210714_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='prouct_quantity',
            new_name='product_quantity',
        ),
    ]
