# Generated by Django 3.2.5 on 2021-07-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_prouct_quantity_products_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
