# Generated by Django 3.2.5 on 2021-07-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_products_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.CharField(choices=[('Shoes', 'Shoes'), ('Top Wear', 'Top Wear'), ('Bottom Wear', 'Bottom Wear')], default='', max_length=50),
        ),
    ]
