# Generated by Django 3.2.5 on 2021-07-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_products_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='wear_by',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
    ]
