# Generated by Django 3.2.5 on 2021-07-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210715_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.BigIntegerField(),
        ),
    ]
