# Generated by Django 3.2.5 on 2021-07-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_shippingaddress_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alt_phone_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
