# Generated by Django 3.2.5 on 2021-07-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_total',
            field=models.FloatField(default=0),
        ),
    ]
