# Generated by Django 3.2.5 on 2021-07-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_cart_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_total',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='tax',
        ),
    ]
